version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    networks:
      - my-custom-network
      
  app:
    command: ["/wait-for-it.sh", "db:3307", "--", "java", "-jar", "/target/demo-0.0.1-SNAPSHOT.jar"]
    build:
      context: .
      dockerfile: Dockerfile
    image: demo:latest
    restart: always
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/java_projects
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-custom-network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: java_projects
      MYSQL_ROOT_USER: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-custom-network

volumes:
  mysql-data:
  jenkins_home:
  
networks:
  my-custom-network:
    driver: bridge