pipeline {
    agent any

    stages {
        stage('Clean Package') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/Chiungue123/Docker-Jenkins.git'

                // Change to the demo project
                dir('demo') {
                 
                    // Run Maven on a Unix agent.
                    sh "./mvnw clean package"

                    echo 'Running maven clean package'
                }
            }
        }

        stage('Build Docker Image') {
		    steps {
		        script {
		        
		        // Change to the demo project
		        dir('demo') {
			            // Building Docker Image with a specific tag
			            sh 'docker build -t demo:${BUILD_NUMBER} -t demo:latest .'
			            
			            echo 'Running docker build'
		        	}
		        }
		    }
		}

		stage('Deploy with Docker Compose') {
		    steps {
		        script {
		        
		        dir('demo') {
			            // Run Docker Compose to build and start the services
	                	sh 'docker-compose up -d --build'
			            
			            echo 'Running docker-compose up -d --build'
		            }
		        }
		    }
		}
		
		stage('Cleanup') {
		    steps {
		        script {
		        
		        dir('demo') {
			            // Clean up dangling images
			            sh 'docker image prune -f'
		        	}
		        }
		    }
		}
    }
}